const link = (base, slug = 'contact') => `${base}${slug}/`;
const arrow = '<svg viewBox="0 0 24 24" class="icon" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';

export function heroVisual(label, base) {
  const visuals = {
    'OUR FLEET': ['country-road.jpg', 'Space for your people.', '15 / 17 / 21 / 25', 'Four seating options for the road ahead'],
    'SCHOOL & ACCESSIBLE TRANSPORT': ['lake-district.jpg', 'Care, every mile.', 'EVERYBODY WELCOME', 'Green countryside beside a winding road'],
    'AIRPORT TRANSFERS': ['airport.jpg', 'Your holiday starts here.', 'TOGETHER, FROM THE START', 'An aeroplane wing above the clouds'],
    'TRIPS & EVENTS': ['wedding.jpg', 'Make a day of it.', 'MOMENTS WORTH SHARING', 'A wedding couple holding a bouquet in warm sunlight'],
    'ABOUT HANNAH COACHES UK': ['country-road.jpg', 'A journey that began in 2010.', 'LANCASHIRE ROOTS', 'An open road through countryside'],
    'CONTACT & ENQUIRIES': ['lake-district.jpg', 'Something to look forward to.', 'LET’S GET YOU THERE', 'A scenic road through the Lake District'],
  };
  const [image, caption, tag, alt] = visuals[label];
  return `<figure class="page-hero-visual"><img src="${base}assets/${image}" alt="${alt}" width="1300" height="1000" fetchpriority="high"><figcaption><span>${tag}</span><strong>${caption}</strong></figcaption><span class="photo-corner" aria-hidden="true">HC / UK</span></figure>`;
}

export function fleetFinder(base) {
  return `<section class="section fleet-finder-section enhanced-only"><div class="container fleet-finder"><div class="finder-controls"><p class="eyebrow">FIND YOUR FIT</p><h2>A place for<br><em>everyone.</em></h2><p>Move the slider to explore a starting point for your group.</p><label class="range-label" for="group-size">Your group <output id="group-count" for="group-size">15 people</output></label><input type="range" id="group-size" min="1" max="30" value="15" aria-describedby="fleet-disclaimer"><div class="range-ends"><span>1 person</span><span>30 people</span></div><div class="size-presets" role="group" aria-label="Choose a group size">${[15,17,21,25].map(n=>`<button type="button" data-group-size="${n}" aria-pressed="${n===15}">${n}<span>people</span></button>`).join('')}</div><label class="check-control"><input type="checkbox" id="finder-access"><span>I’d like to discuss accessible travel</span></label><p id="fleet-disclaimer" class="finder-fineprint">A seating guide, subject to availability. Luggage, equipment and access requirements can change the vehicle and capacity you need.</p></div><div class="finder-result"><div class="finder-result-top"><span>YOUR GROUP AT A GLANCE</span><span class="finder-pill" id="finder-capacity">15 seats</span></div><div class="bus-plan" aria-hidden="true"><div class="bus-windscreen"></div><div id="finder-seats" class="finder-seats"></div><span class="bus-door"></span></div><div class="seat-legend"><span><i></i>Your group</span><span><i></i>Other seats</span></div><div class="finder-result-copy" aria-live="polite" aria-atomic="true"><h3 id="finder-title">Explore our 15-seater</h3><p id="finder-description">A seating starting point for 15 passengers.</p></div><a id="finder-enquire" class="button button-white" href="${link(base)}?seats=15">Discuss this journey ${arrow}</a><span class="plan-caption">Illustration only. Vehicle layouts vary.</span></div></div></section>`;
}

export function journeyExplorer(base) {
  const items = [
    ['weekends','The great escape','country-road.jpg','A weekend away. A whole group of memories.','Fresh air, a change of scene and your favourite company. Start with a destination and we’ll talk through the journey.','UK resort or weekend trip'],
    ['golf','Out on the course','golf.jpg','Your next round starts here.','Bring your group together for a day on the course. Tell us about tee times and golf bags when you enquire.','Golf trip'],
    ['football','For the love of the game','football.jpg','Same team. Same journey.','Get your match-day group together and make the most of the day, from the first pickup to the journey home.','Football trip'],
    ['weddings','A day to remember','wedding.jpg','Everyone together for your big moment.','Help your guests share the celebration. Talk to us about your venues, pickup points and return plans.','Wedding or celebration'],
  ];
  return `<section class="section journey-explorer"><div class="container"><div class="section-heading"><div><p class="eyebrow">WHAT’S YOUR KIND OF DAY?</p><h2>Find your<br><em>next good memory.</em></h2></div><p>A little inspiration for the road ahead.<br>Choose an occasion to explore.</p></div><div class="explorer-tabs enhanced-only" role="tablist" aria-label="Explore trip ideas">${items.map(([id,title],i)=>`<button role="tab" id="tab-${id}" aria-controls="panel-${id}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-trip-tab="${id}"><span>0${i+1}</span>${title}</button>`).join('')}</div>${items.map(([id,title,img,headline,desc,service],i)=>`<div class="explorer-panel" id="panel-${id}" role="tabpanel" aria-labelledby="tab-${id}" tabindex="0" ${i?'hidden':''}><div class="explorer-image"><img src="${base}assets/${img}" alt="${title}" width="1300" height="900" loading="lazy"><span class="explorer-image-label">${title}</span></div><div class="explorer-copy"><span class="explorer-counter">0${i+1}<span> / 04</span></span><h3>${headline}</h3><p>${desc}</p><a class="button" href="${link(base)}?service=${encodeURIComponent(service)}">Make a plan ${arrow}</a><span class="explorer-small">15, 17, 21 & 25 seaters</span></div></div>`).join('')}</div></section>`;
}

export function accessChecklist(base) {
  return `<section class="section enhanced-only"><div class="container access-planner"><div><p class="eyebrow">YOUR JOURNEY, CONSIDERED</p><h2>Let’s start with<br><em>what you need.</em></h2><p>Choose the things you’d like to discuss. We’ll add them to your enquiry, ready for a conversation with M Latif.</p><p class="finder-fineprint">You don’t need to share a diagnosis or medical details. Suitability and availability are confirmed personally before booking.</p></div><div><fieldset class="access-options"><legend>What would you like to discuss?</legend>${['Wheelchair or mobility equipment','Boarding assistance','Space for a companion','A regular school journey'].map((label,i)=>`<label><input type="checkbox" value="${label}" name="access-topic"><span class="access-option-number">0${i+1}</span><span>${label}</span><span class="access-option-check" aria-hidden="true">✓</span></label>`).join('')}</fieldset><p id="access-summary" aria-live="polite">Choose any that apply, or start a general conversation.</p><a id="access-enquire" class="button" href="${link(base)}?service=Accessible+transport">Discuss my journey ${arrow}</a></div></div></section>`;
}

export function airportPicker(base) {
  return `<div class="airport-picker enhanced-only"><label for="airport-choice">Where are you flying from?</label><select id="airport-choice"><option value="">Choose your airport</option><option>Manchester Airport</option><option>Liverpool John Lennon Airport</option><option>Leeds Bradford Airport</option><option>Another UK airport</option></select><a class="ticket-link" id="airport-enquire" href="${link(base)}?service=Airport+transfer">Plan this transfer ${arrow}</a><p>Routes and timings are subject to confirmation.</p></div>`;
}

export function planner(base) {
  const services = [['Airport transfer','01','Airport'],['School transport','02','School'],['Golf trip','03','Golf'],['Football trip','04','Football'],['UK resort or weekend trip','05','A getaway'],['Wedding or celebration','06','A celebration']];
  return `<div class="scroll-progress" aria-hidden="true"><span></span></div><div class="floating-actions enhanced-only"><button class="quick-plan" type="button" data-open-planner>${arrow}<span>Plan a journey</span></button><button class="back-top" type="button" aria-label="Back to top" hidden>↑</button></div>
  <dialog id="journey-planner" aria-labelledby="planner-heading"><div class="planner-layout"><div class="planner-photo"><img src="${base}assets/lake-district.jpg" alt="" width="1000" height="1400" loading="lazy"><div><span>HANNAH COACHES UK</span><h2>A little planning.<br><em>A lot to look<br>forward to.</em></h2><p>Let’s get everyone together.</p></div></div><div class="planner-content"><button type="button" class="planner-close" aria-label="Close journey planner">×</button><p class="eyebrow">LET’S MAKE IT HAPPEN</p><h2 id="planner-heading">Your journey<br>starts here.</h2><form id="planner-form" action="${link(base)}" method="get"><fieldset class="occasion-options"><legend>01 / What’s the occasion?</legend>${services.map(([value,num,label])=>`<label><input type="radio" name="service" value="${value}" required><span><small>${num}</small>${label}${arrow}</span></label>`).join('')}</fieldset><div class="planner-fields"><div class="field"><label for="planner-passengers">02 / Your group size</label><input type="number" name="passengers" id="planner-passengers" min="1" max="100" value="15" required></div><div class="field"><label for="planner-destination">03 / Where to?</label><input name="destination" id="planner-destination" maxlength="200" placeholder="Destination or venue"></div></div><label class="check-control"><input type="checkbox" name="accessible" value="yes"><span>I’d like to discuss accessibility</span></label><button class="button" type="submit">Continue to my enquiry ${arrow}</button><p class="planner-note">We’ll carry these details to your enquiry. No booking or payment is made here.</p><a class="planner-prep-link" href="${base}trips-events/#trip-tool">Already planning a trip? Open your preparation toolkit.</a></form></div></div></dialog>`;
}
