import { airports, regions } from './airports.js';
const escape = value => value.replaceAll('&','&amp;');
export function flightChecker(base, icon) {
  return `<section class="flight-strip"><div class="container"><span>${icon('plane')} ${airports.length} UK airports</span><span>Official airport flight boards</span><a href="#flight-transfer">Connect your Hannah Coaches journey ${icon('arrow')}</a></div></section>
  <section id="flight-checker" class="section flight-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">FROM FLIGHT CHECK TO FRONT DOOR</p><h2>Check the flight.<br><em>Plan the journey.</em></h2></div><p>Live arrivals and departures open on the airport’s own website. Return here to arrange your group transfer.</p></div>
  <form id="flight-form" data-base="${base}" class="flight-layout enhanced-only">
    <div class="flight-board"><div class="flight-board-top"><span>01 / YOUR AIRPORT</span>${icon('plane')}</div><div class="field"><label for="flight-airport">Choose a UK airport</label><select id="flight-airport" name="airport">${regions.map(region=>`<optgroup label="${escape(region)}">${airports.filter(item=>item.region===region).map(item=>`<option value="${item.code}">${item.name} (${item.code})</option>`).join('')}</optgroup>`).join('')}</select></div>
    <fieldset class="flight-direction"><legend>Which flight board?</legend><label><input type="radio" name="direction" value="arrivals" checked><span>↘ Arrivals</span></label><label><input type="radio" name="direction" value="departures"><span>↗ Departures</span></label></fieldset>
    <div class="flight-airport-display" aria-live="polite" aria-atomic="true"><span id="flight-code">MAN</span><h3 id="flight-airport-name">Manchester</h3><p id="flight-board-description">Arrivals at Manchester</p></div>
    <a id="flight-live-link" class="button button-white" href="https://www.manchesterairport.co.uk/arrivals/" target="_blank" rel="noopener noreferrer"><span id="flight-live-label">Open live arrivals</span> <span aria-hidden="true">↗</span><span class="flight-sr"> (opens a new tab)</span></a><p class="flight-source" id="flight-source">Source: manchesterairport.co.uk</p><p class="flight-board-note" id="flight-source-note">Use the airport’s flight search to find your flight.</p>
    <div class="field"><label for="flight-number">Flight number (optional)</label><input id="flight-number" name="flight" maxlength="20" placeholder="e.g. LS123" autocomplete="off" autocapitalize="characters" spellcheck="false" aria-describedby="flight-number-help"></div><p class="flight-board-note" id="flight-number-help">Copy it to search on the airport board. We’ll also include it in your transport enquiry.</p><button id="flight-copy" class="flight-copy" type="button">Copy flight number ${icon('arrow')}</button><p id="flight-copy-status" class="flight-board-note" role="status"></p>
    <p class="flight-board-note flight-status-note">Flight status is provided on the airport website. This page does not display live flight data, monitor delays or update a transport booking automatically.</p></div>
    <div class="flight-transfer" id="flight-transfer"><p class="eyebrow">02 / YOUR HANNAH COACHES JOURNEY</p><h3 id="flight-transfer-title">Landing? Let’s get you home.</h3><p id="flight-route-summary" aria-live="polite">Pickup from Manchester Airport. Tell us where your group is heading.</p>
    <div class="form-grid"><div class="field"><label for="flight-terminal">Terminal (if known)</label><input id="flight-terminal" name="terminal" maxlength="30" placeholder="Confirm with your airline"></div><div class="field"><label for="flight-date">Flight date at UK airport</label><input type="date" id="flight-date" name="flightDate"></div><div class="field"><label for="flight-time" id="flight-time-label">Scheduled landing time (UK)</label><input type="time" id="flight-time" name="flightTime" aria-describedby="flight-time-help"></div><div class="field"><label for="flight-transfer-date">Requested transfer date</label><input type="date" id="flight-transfer-date" name="transferDate" aria-describedby="flight-time-help"></div></div>
    <p class="flight-hint" id="flight-time-help">Flight time is not pickup time. Use the UK airport’s local date and time. An overnight flight or early departure may need a transfer on a different date. M Latif will agree collection time with you.</p>
    <div class="form-grid"><div class="field full-field"><label for="flight-location" id="flight-location-label">Your destination town or postcode <span>*</span></label><input id="flight-location" name="location" required maxlength="200" placeholder="e.g. Nelson, Lancashire"></div><div class="field"><label for="flight-passengers">Passengers <span>*</span></label><input type="number" id="flight-passengers" name="passengers" required min="1" max="100" step="1" value="15"></div><div class="field"><label for="flight-bags">Luggage items (optional)</label><input type="number" id="flight-bags" name="bags" min="0" max="200" step="1" placeholder="Suitcases and large bags"></div></div>
    <label class="check-control"><input id="flight-access" name="accessible" type="checkbox"><span>I’d like to discuss accessible transport</span></label><p class="flight-hint" id="flight-capacity" aria-live="polite">15, 17, 21 and 25 seaters. We’ll confirm space for your group and luggage.</p><button class="button" type="submit">Enquire with Hannah Coaches ${icon('arrow')}</button><p class="flight-hint">Review your details on the next page, then send an email enquiry. Every route is subject to availability and agreement. No booking is confirmed here.</p><a class="text-link" href="tel:+447971117677">Flight plans changed? Call M Latif ${icon('phone')}</a></div>
  </form><noscript><p>Use the official airport links below to check flights, then <a class="text-link" href="${base}contact/?service=Airport+transfer">enquire about your airport transfer</a> or call <a href="tel:+447971117677">07971 117677</a>.</p></noscript></div></section>
  <section class="section airport-directory" id="airport-directory"><div class="container"><div class="section-heading"><div><p class="eyebrow">ACROSS THE UK</p><h2>Your airport.<br><em>One place to start.</em></h2></div><p>Major hubs and regional airports across all four UK nations. Official links open in a new tab.</p></div><div class="airport-filters enhanced-only"><div class="field"><label for="airport-search">Find an airport</label><input type="search" id="airport-search" placeholder="Search by name or code, e.g. Manchester or MAN" autocomplete="off"></div><div class="field"><label for="airport-region">Region</label><select id="airport-region"><option value="">All UK regions</option>${regions.map(region=>`<option>${escape(region)}</option>`).join('')}</select></div><button type="button" id="airport-clear" class="button button-outline">Clear filters</button></div><p id="airport-count" class="flight-hint" role="status">${airports.length} airports</p><div class="airport-cards">${airports.map(item=>`<article class="airport-card" data-airport-card="${item.code}"><div class="airport-card-top"><span>${item.code}</span>${icon('plane')}</div><h3>${item.name}</h3><p>${escape(item.region)}</p><div class="airport-card-links"><a href="${item.arrivals}" target="_blank" rel="noopener noreferrer" aria-label="${item.name} arrivals (opens a new tab)">Arrivals ↗</a><a href="${item.departures}" target="_blank" rel="noopener noreferrer" aria-label="${item.name} departures (opens a new tab)">Departures ↗</a></div><a class="text-link" href="${base}flight-checker/?airport=${item.code}#flight-checker" data-choose-airport="${item.code}">Plan a transfer ${icon('arrow')}</a></article>`).join('')}</div><p id="airport-empty" hidden>No airports match. Try another name or code, or clear the filters.</p>
  <div class="flight-advice"><div><span>01</span><h3>Check before you travel</h3><p>Confirm the latest status, terminal and check-in guidance with your airport and airline. A delayed departure does not automatically change your required check-in time.</p></div><div><span>02</span><h3>Agree your collection</h3><p>Allow for baggage reclaim, border checks and any assistance. Confirm the meeting point and collection time directly with M Latif.</p></div><div><span>03</span><h3>Keep us in the loop</h3><p>If your flight, terminal or travel date changes, call <a href="tel:+447971117677">07971 117677</a> to discuss your transport. Changes need to be agreed.</p></div></div></div></section>`;
}
