import { heroVisual, fleetFinder, journeyExplorer, accessChecklist, airportPicker, planner } from './experience.mjs';
import { tripTool } from './trip-tool.mjs';
import { staysPlanner } from './stays.mjs';

export const pages = [
  { slug: '', nav: 'Home', title: 'Minibus & Coach Hire in Lancashire', description: 'Hannah Coaches UK: 15, 17, 21 and 25 seaters for school transport, accessible travel, airport transfers, weddings and days out. Established 2010. Call 07971 117677.' },
  { slug: 'our-fleet', nav: 'Our Fleet', title: 'Our Fleet · 15, 17, 21 & 25 Seaters', description: 'Choose a 15, 17, 21 or 25 seater for your next group journey. Speak to Hannah Coaches UK about passengers, luggage and accessible transport.' },
  { slug: 'school-transport', nav: 'School Transport', title: 'School & Accessible Transport', description: 'Lancashire approved school transport with fully licensed, DBS checked drivers. Specialised access for disabled passengers. Everyone is welcome.' },
  { slug: 'airport-transfers', nav: 'Airport Transfers', title: 'Group Airport Transfers', description: 'Start your holiday together with Hannah Coaches UK. Group airport transfers from Lancashire, with 15 to 25 seaters and return journeys by arrangement.' },
  { slug: 'trips-events', nav: 'Trips & Events', title: 'Weekend Trips, Weddings & Events', description: 'Travel together for golf trips, football matches, UK resorts, weddings and weekend breaks. Arrange group transport with Hannah Coaches UK.' },
  { slug: 'stays-travel', nav: 'Stays & Travel', title: 'Booking.com & Airbnb Stays with Group Transport', description: 'Find accommodation on Booking.com or Airbnb, then carry your destination, dates and group details into a Hannah Coaches transport enquiry.' },
  { slug: 'about', nav: 'About Us', title: 'About Hannah Coaches UK', description: 'Welcoming passengers since 2010. Meet Hannah Coaches UK, a Lancashire approved operator with licensed transport manager M Latif.' },
  { slug: 'contact', nav: 'Contact', title: 'Contact & Request a Quote', description: 'Speak to M Latif at Hannah Coaches UK on 07971 117677 or email safetravel77@outlook.com. Request a quote for your next group journey.' },
];

export const googleReviews = 'https://www.google.com/maps/search/?api=1&query=Hannah+Coaches+UK+Ltd+Nelson+Lancashire';
const paths = {
  arrow: '<path d="M4 12h15m-6-6 6 6-6 6"/>',
  phone: '<path d="M7 3H4a1 1 0 0 0-1 1c0 9.4 7.6 17 17 17a1 1 0 0 0 1-1v-3l-5-2-2 2a15 15 0 0 1-7-7l2-2-2-5Z"/>',
  bus: '<rect x="4" y="3" width="16" height="16" rx="3"/><path d="M4 11h16M8 19v2m8-2v2M8 15h.01M16 15h.01M8 7h8"/>',
  shield: '<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  school: '<path d="m2 8 10-5 10 5-10 5-10-5Zm4 3v6l6 3 6-3v-6m4-3v8"/>',
  plane: '<path d="m21 3-7 18-3-8-8-3 18-7ZM11 13 21 3"/>',
  heart: '<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
  access: '<circle cx="12" cy="4" r="2"/><path d="m12 8-1 6h6l3 6M12 10h5M8 10a6 6 0 1 0 7 10"/>',
  pin: '<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
  mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',
  people: '<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 4a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5v2"/>',
  sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
  flag: '<path d="M5 21V3c5-4 9 4 14 0v10c-5 4-9-4-14 0"/>',
};
export const icon = (name, cls = '') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.55" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.bus}</svg>`;
const url = (base, slug = '') => `${base}${slug}${slug ? '/' : ''}`;
const button = (label, href, type = '') => `<a class="button ${type}" href="${href}">${label}${icon('arrow')}</a>`;
const eyebrow = (text) => `<p class="eyebrow"><span></span>${text}</p>`;
const badge = (name, text) => `<span class="trust-item">${icon(name)}${text}</span>`;
const brand = (base) => `<a class="brand" href="${base}" aria-label="Hannah Coaches UK home"><span class="brand-mark">H<span></span></span><span class="brand-name">HANNAH<span>COACHES UK <i>·</i> EST. 2010</span></span></a>`;

function header(page, base) {
  return `<a href="#main" class="skip-link">Skip to content</a>
  <div class="topbar" role="region" aria-label="Contact information"><div class="container"><span>From Lancashire. For every journey.</span><span class="topbar-right"><span>Fully licensed & DBS checked</span><a href="tel:+447971117677">${icon('phone')}07971 117677</a></span></div></div>
  <header class="site-header"><div class="container header-inner">${brand(base)}
  <button class="menu-toggle" type="button" aria-label="Toggle navigation menu" aria-expanded="false" aria-controls="main-nav"><span class="menu-lines"></span><span class="menu-label">Menu</span></button>
  <nav id="main-nav" aria-label="Main navigation">${pages.map(p => `<a href="${url(base, p.slug)}" ${p.slug === page.slug ? 'aria-current="page"' : ''}>${p.nav}</a>`).join('')}</nav>
  <a class="header-quote" href="${url(base, 'contact')}#enquiry">Get a quote ${icon('arrow')}</a></div></header>`;
}

function footer(base) {
  return `<footer class="site-footer"><div class="container footer-grid"><div>${brand(base)}<p>Good journeys. Great company.<br>Welcoming you aboard since 2010.</p><a class="footer-review" href="${googleReviews}" target="_blank" rel="noopener noreferrer">Find us & check reviews on Google ${icon('arrow')}</a></div>
  <div><h2>Explore</h2><a href="${url(base,'trips-events')}#trip-tool">Trip companion</a>${pages.slice(1, 4).map(p => `<a href="${url(base,p.slug)}">${p.nav}</a>`).join('')}</div>
  <div><h2>Your next journey</h2>${pages.slice(4).map(p => `<a href="${url(base,p.slug)}">${p.nav}</a>`).join('')}</div>
  <div><h2>Let's talk travel</h2><a class="footer-phone" href="tel:+447971117677">07971 117677</a><a href="mailto:safetravel77@outlook.com">safetravel77@outlook.com</a><p>M Latif<br>Licensed transport manager</p></div></div>
  <div class="container footer-bottom"><span>© ${new Date().getFullYear()} Hannah Coaches UK. Everybody welcome.</span><span>Lancashire approved <i>·</i> Established 2010</span><a href="${url(base, 'contact')}#privacy">Privacy & enquiries</a></div></footer>`;
}

const cta = (base, heading = 'Where shall we take you?') => `<section class="cta-section"><div class="container cta-inner"><div>${eyebrow('YOUR NEXT JOURNEY')}<h2>${heading}</h2><p>A day out, a special occasion or the everyday. Let’s get you there.</p></div><div>${button('Plan your journey',url(base,'contact'),'button-white')}<a class="cta-phone" href="tel:+447971117677">Or call 07971 117677</a></div></div></section>`;
const trustStrip = () => `<div class="trust-strip"><div class="container">${badge('shield','Fully licensed drivers')}${badge('check','DBS checked')}${badge('pin','Lancashire approved')}${badge('access','Everybody welcome')}</div></div>`;
const faq = (items) => `<div class="faq-list">${items.map(([q,a])=>`<details><summary>${q}<span>+</span></summary><p>${a}</p></details>`).join('')}</div>`;
const stepList = (items) => `<div class="steps">${items.map(([title,body],i)=>`<div class="step"><span>0${i+1}</span><h3>${title}</h3><p>${body}</p></div>`).join('')}</div>`;
const pageHero = (base, label, title, intro, extra = '') => `<section class="page-hero"><div class="container"><div class="breadcrumb"><a href="${base}">Home</a><span>/</span>${label}</div><div class="page-hero-grid"><div class="page-hero-copy">${eyebrow(label)}<h1>${title}</h1><p class="hero-intro">${intro}</p>${extra}</div>${heroVisual(label,base)}</div></div></section>`;

function home(base) {
  const services = [
    ['school','01','School & accessible travel','A little reassurance for the everyday journey. School transport with care and specialised access.','school-transport','Explore school transport'],
    ['plane','02','Airport transfers','The holiday starts at your front door. Get the whole group to the airport together.','airport-transfers','Plan an airport transfer'],
    ['sun','03','Trips & special occasions','From match days to wedding days. Make getting there part of the good memories.','trips-events','Discover trips & events'],
  ];
  return `<section class="home-hero"><img class="hero-photo" src="${base}assets/lake-district.jpg" alt="A winding road through the green hills of the Lake District" fetchpriority="high" width="2200" height="1467"><div class="hero-shade"></div><div class="container hero-content">${eyebrow('LANCASHIRE ROOTS. UK-WIDE JOURNEYS.')}<h1>Good journeys.<br><em>Great company.</em></h1><p>Wherever you’re heading, go together.<br>Minibus & coach hire with a personal touch,<br class="desktop-break"> from a team that cares.</p><div class="hero-actions">${button('Let’s plan your journey',url(base,'contact'))}<a class="hero-secondary" href="${url(base,'our-fleet')}">Meet our fleet ${icon('arrow')}</a></div><div class="hero-footnote"><span class="small-rule"></span>EVERYBODY WELCOME. ALWAYS.</div></div><div class="hero-side-note">THE JOURNEY IS PART OF THE DAY.</div><a href="#journeys" class="scroll-hint">Explore a little further <span>↓</span></a><div class="hero-est"><span>Est.</span><strong>2010</strong><span>Travel with care</span></div></section>
  ${trustStrip()}
  <section id="journeys" class="section services-section"><div class="container"><div class="section-heading"><div>${eyebrow('A JOURNEY FOR EVERY OCCASION')}<h2>Your plans.<br>Our pleasure.</h2></div><p>The school run. The big day. The weekend away.<br>Whatever brings you together, we’ll help you get there.</p></div><div class="service-grid">${services.map(([ic,n,title,desc,slug,link])=>`<a class="service-card" href="${url(base,slug)}"><div class="service-photo"><img src="${base}assets/${ic==='school'?'country-road.jpg':ic==='plane'?'airport.jpg':'wedding.jpg'}" alt="" loading="lazy" width="800" height="520"></div><div class="service-top"><span class="icon-tile">${icon(ic)}</span><span class="card-number">${n}</span></div><h3>${title}</h3><p>${desc}</p><span class="text-link">${link}${icon('arrow')}</span></a>`).join('')}</div></div></section>
  <div class="container"><a class="prep-home-link" href="${url(base,'trips-events')}#trip-tool"><span><strong>Organising a group trip?</strong><small>Build your checklist, work out timings and create a trip pack.</small></span><span>Open the trip companion ${icon('arrow')}</span></a></div>${journeyExplorer(base)}<section class="fleet-band"><div class="container fleet-band-inner"><div>${eyebrow('ROOM FOR YOUR WHOLE GROUP')}<h2>Small group.<br>Big adventure.</h2><p>Four sizes. One friendly standard of care.</p><a class="text-link" href="${url(base,'our-fleet')}">Find your fit ${icon('arrow')}</a></div><div class="fleet-numbers">${[15,17,21,25].map(n=>`<a href="${url(base,'our-fleet')}#seater-${n}" aria-label="Explore our ${n} seaters"><span>${n}</span><span>SEATERS</span>${icon('people')}</a>`).join('')}</div></div></section>
  <section class="section"><div class="container welcome-grid"><div class="welcome-image"><img src="${base}assets/country-road.jpg" alt="An open country road winding through the Lake District" loading="lazy" width="1400" height="933"><div class="image-caption">A local team. A world of possibilities.</div></div><div class="welcome-copy">${eyebrow('A WARM WELCOME, SINCE 2010')}<h2>More than a seat.<br>A sense of<br><em>being looked after.</em></h2><p>At Hannah Coaches UK, we believe the journey matters as much as the destination. We’re here for families, schools, friends and communities across Lancashire.</p><p>With fully licensed, DBS checked drivers and licensed transport manager M Latif, you’ll have a real person to talk to from your first enquiry.</p>${button('Get to know Hannah Coaches',url(base,'about'),'button-outline')}</div></div></section>
  <section class="review-strip"><div class="container"><span class="google-g" aria-hidden="true">G</span><div><h2>Good journeys are worth talking about.</h2><p>Find Hannah Coaches UK on Google and see what passengers have to say.</p></div><a class="text-link" href="${googleReviews}" target="_blank" rel="noopener noreferrer">Check Google reviews ${icon('arrow')}</a></div></section>${cta(base)}`;
}

function fleet(base) {
  const descriptions = {15:'A lovely fit for smaller groups, family occasions and days away.',17:'Bring a few more people along for your airport run or weekend plans.',21:'Keep your club, school group or wedding guests travelling together.',25:'Our largest seating option for bigger groups and shared adventures.'};
  return `${pageHero(base,'OUR FLEET','The right size.<br><em>The same warm welcome.</em>','15, 17, 21 or 25 seats. Find the right fit for your people, your plans and everything coming along for the ride.')}
  ${fleetFinder(base)}<section class="section"><div class="container"><div class="fleet-grid">${[15,17,21,25].map(n=>`<article class="fleet-card" id="seater-${n}"><div class="fleet-card-art"><span class="fleet-big-number">${n}</span><span class="fleet-art-label">SEATERS</span><div class="seat-map" aria-hidden="true">${Array.from({length:n},()=>'<span></span>').join('')}</div></div><div class="fleet-card-body"><p class="eyebrow">TRAVEL TOGETHER</p><h2>${n}-seater hire</h2><p>${descriptions[n]}</p><ul class="check-list"><li>${icon('check')}Fully licensed driver</li><li>${icon('check')}DBS checked</li><li>${icon('check')}Your itinerary, planned with you</li></ul>${button('Enquire about '+n+' seats',url(base,'contact')+'?seats='+n,'button-outline')}</div></article>`).join('')}</div><div class="notice">${icon('bus')}<div><h3>People, bags and accessibility. Let’s plan it properly.</h3><p>Seating capacity depends on the vehicle arrangement. Tell us about luggage, golf clubs, wheelchairs or mobility equipment so we can confirm a suitable vehicle and available capacity before you book.</p></div></div></div></section>
  <section class="section pale-section"><div class="container split-section"><div>${eyebrow('A LITTLE HELP CHOOSING')}<h2>Room for<br>the details.</h2><p>Not sure which size is right? Speak to M Latif on <a href="tel:+447971117677">07971 117677</a>.</p></div>${faq([['Can we bring suitcases or golf clubs?','Please include the number and size of bags or equipment in your enquiry. We’ll confirm luggage space and the right vehicle before you book.'],['Is accessible transport available?','We offer specialised access for disabled passengers. Contact us with your boarding, wheelchair and seating requirements so we can discuss the right arrangement and confirm availability.'],['Can we request more than 25 seats?','Our stated vehicle sizes are 15, 17, 21 and 25 seats. If your group is larger, contact us to discuss whether we can accommodate your plans.']])}</div></section>${cta(base)}`;
}

function school(base) {
  return `${pageHero(base,'SCHOOL & ACCESSIBLE TRANSPORT','Care comes first.<br><em>Every school day.</em>','School transport that puts people at the heart of the journey. Supporting schools, families and disabled passengers with a welcoming, personal approach.',button('Discuss your school transport',url(base,'contact')+'?service=School+transport'))}${trustStrip()}
  <section class="section"><div class="container split-section"><div>${eyebrow('REASSURANCE FOR THE ROUTINE')}<h2>A familiar journey.<br>Thoughtfully arranged.</h2></div><div class="prose"><p>From home-to-school travel to school outings, Hannah Coaches UK helps groups get where they need to be. We’re Lancashire approved, and our drivers are fully licensed and DBS checked.</p><p>Talk to licensed transport manager M Latif about your route, passenger numbers, timings and the support your group needs. We’ll discuss availability and agree the arrangements with you before travel.</p></div></div><div class="container feature-grid"><article>${icon('shield')}<h3>People you can trust</h3><p>Fully licensed, DBS checked drivers, with a licensed transport manager overseeing your enquiry.</p></article><article>${icon('school')}<h3>School journeys</h3><p>Discuss regular school transport, educational outings and group travel around your school’s needs.</p></article><article>${icon('people')}<h3>A personal point of contact</h3><p>Speak directly to M Latif to discuss the details and ask questions about the journey.</p></article></div></section>
  <section class="access-section"><div class="container access-grid"><div class="access-symbol">${icon('access')}<span>EVERYBODY WELCOME</span></div><div>${eyebrow('ACCESSIBLE TRAVEL')}<h2>Different needs.<br>The same welcome.</h2><p>We offer specialised access for disabled passengers, including school transport. Every passenger’s needs are different, so a conversation is the best place to start.</p><p>Tell us about boarding assistance, wheelchair or mobility equipment, seating requirements and anyone travelling with you. We’ll confirm vehicle suitability, capacity and availability before accepting a booking.</p>${button('Talk to us about access',url(base,'contact')+'?service=Accessible+transport','button-white')}</div></div></section>
  <section class="section"><div class="container">${eyebrow('LET’S GET THE DETAILS RIGHT')}<h2>One conversation.<br>A considered plan.</h2>${stepList([['Tell us about the journey','Share your pickup points, destination, school times and passenger numbers.'],['Discuss individual needs','Let us know about access, seating or assistance requirements. No need to include private medical details in an online enquiry.'],['Agree the arrangements','We’ll discuss a suitable vehicle, availability and your quote before you decide.']])}</div></section>${accessChecklist(base)}${cta(base,'Let’s make the everyday easier.')}`;
}

function airports(base) {
  return `${pageHero(base,'AIRPORT TRANSFERS','Start the holiday.<br><em>Before the take-off.</em>','One group. One journey. Arrange an airport transfer from Lancashire and enjoy travelling together from the very start.',button('Enquire about an airport transfer',url(base,'contact')+'?service=Airport+transfer'))}
  <section class="section"><div class="container welcome-grid"><div class="airport-panel"><div class="ticket-heading">HANNAH COACHES UK<span>YOUR HOLIDAY STARTS HERE</span></div><div class="ticket-route"><div><span>FROM</span><strong>Your<br>doorstep</strong></div>${icon('plane')}<div><span>TO</span><strong id="airport-ticket-destination">Your<br>airport</strong></div></div>${airportPicker(base)}<div class="ticket-bottom"><div><span>PASSENGERS</span><strong>Your favourite people</strong></div><div><span>THE PLAN</span><strong>Travel together</strong></div></div></div><div>${eyebrow('LESS TO ORGANISE. MORE TO ENJOY.')}<h2>All aboard.<br>Holiday mode on.</h2><p>Skip the separate cars and coordinate your group’s airport journey in one place. Whether it’s a family holiday, a friends’ getaway or a group trip, tell us where you’re flying from and when.</p><p>We offer 15, 17, 21 and 25 seaters. Your luggage matters too. We’ll confirm the right vehicle for your passengers and bags when you enquire.</p><a class="text-link" href="${url(base,'our-fleet')}">Explore our seating options ${icon('arrow')}</a></div></div></section>
  <section class="section pale-section"><div class="container">${eyebrow('A SMOOTHER START')}<h2>Your trip, planned around you.</h2>${stepList([['Share your flight details','Tell us your airport, flight date, departure time and where your group needs collecting.'],['Make room for everyone','Confirm passenger numbers, luggage and any accessibility needs so we can discuss a suitable vehicle.'],['Plan the journey home','Need a return transfer? Include your return flight date and arrival time in the same enquiry.']])}</div></section>
  <section class="section"><div class="container split-section"><div>${eyebrow('BEFORE YOU FLY')}<h2>A few things<br>you might ask.</h2></div>${faq([['Which airports can we travel to?','Tell us which UK airport you’re using and your pickup location in Lancashire. We’ll confirm whether we can accommodate your route and timings.'],['Can you arrange an early morning or weekend transfer?','Include your required date and time in the enquiry. Early, late and weekend journeys are subject to availability and are agreed before booking.'],['Is our booking confirmed when we send an enquiry?','No. An enquiry starts the conversation. Your booking is confirmed only when we have agreed the journey details, price and booking arrangements with you.'],['Can we book accessible airport transport?','Please discuss access requirements, mobility equipment and luggage with M Latif before booking so we can confirm vehicle suitability and capacity.']])}</div></section>${cta(base,'Your holiday deserves a good start.')}`;
}

function trips(base) {
  const trips = [['flag','Golf trips','The whole group. The whole day.','Get your golfing group to the course together. Tell us about tee times, collection points and golf bags so we can plan a suitable vehicle.','Golf trip'],['people','Football trips','Bring your match-day people.','Travel together to support your team or attend a football event. Share the fixture, venue, group size and your return plans.','Football trip'],['sun','UK resorts & weekends','A change of scene, together.','Seaside days, resort stays and weekends away. Choose your destination, gather your group and let’s talk about the journey.','UK resort or weekend trip'],['heart','Weddings & celebrations','Good company for your big day.','Bring guests together for your wedding or special occasion. Discuss venues, pickup points and return times for a plan that fits the day.','Wedding or celebration']];
  return `${pageHero(base,'TRIPS & EVENTS','The best days<br><em>are shared.</em>','From the first tee to the final whistle. From a weekend by the sea to a once-in-a-lifetime celebration. Make the journey part of the occasion.',button('Open the trip companion',url(base,'trips-events')+'#trip-tool'))}
  ${tripTool(base)}${journeyExplorer(base)}<section class="section"><div class="container trip-grid">${trips.map(([ic,title,tag,desc,service],i)=>`<article class="trip-card"><div class="trip-photo"><img src="${base}assets/${['golf.jpg','football.jpg','country-road.jpg','wedding.jpg'][i]}" alt="" loading="lazy" width="1000" height="650"></div><span class="trip-index">0${i+1}</span><span class="icon-tile">${icon(ic)}</span><h2>${title}</h2><h3>${tag}</h3><p>${desc}</p><a class="text-link" href="${url(base,'contact')}?service=${encodeURIComponent(service)}">Plan ${i===0?'a golf trip':i===1?'a football trip':i===2?'a getaway':'your celebration'} ${icon('arrow')}</a></article>`).join('')}</div></section>
  <section class="scenic-banner"><img src="${base}assets/lake-district.jpg" alt="Green Lake District hills and a winding country road" loading="lazy" width="2200" height="1467"><div class="container">${eyebrow('MAKE A DAY OF IT')}<h2>A good day out<br>starts with a<br><em>good way there.</em></h2><p>You bring the plans. We’ll help with the journey.</p></div></section>
  <section class="section"><div class="container split-section"><div>${eyebrow('YOUR DAY. YOUR DETAILS.')}<h2>Let’s get everyone<br>on the same page.</h2></div><div><ul class="large-list"><li><span>01</span>Where are you going, and when?</li><li><span>02</span>How many people are coming along?</li><li><span>03</span>Any extra luggage, equipment or access needs?</li><li><span>04</span>One-way, return or multiple stops?</li></ul><p>Share the details with M Latif and we’ll discuss availability and a quote for your trip.</p></div></div></section>${cta(base,'Something good in the diary?')}`;
}

function stays(base) {
  return `${pageHero(base,'STAYS & TRAVEL','Find your stay.<br><em>We’ll help you<br>get there.</em>','A hotel weekend. A home away from home. Find your place on Booking.com or Airbnb, then arrange the journey together with Hannah Coaches.',button('Start planning your stay','#stay-planner'))}${staysPlanner(base, icon)}${cta(base,'A lovely place. A good way there.')}`;
}

function about(base) {
  return `${pageHero(base,'ABOUT HANNAH COACHES UK','Lancashire roots.<br><em>A personal touch.</em>','Bringing people together and taking them places since 2010. We’re Hannah Coaches UK, and everybody is welcome.')}
  <section class="section"><div class="container about-grid"><div class="est-panel"><img src="${base}assets/country-road.jpg" alt="" loading="lazy" width="1000" height="1200"><span>TRAVEL WITH CARE</span><strong>2010</strong><span>THE YEAR OUR JOURNEY BEGAN</span><div>${icon('bus')}</div></div><div>${eyebrow('OUR STORY')}<h2>For the everyday.<br>And the unforgettable.</h2><p>We’ve been helping people travel together since 2010. From school transport to airport runs, golf outings, football trips, UK resorts and weddings, our work starts with understanding your journey.</p><p>We keep things personal. Tell us your plans, ask your questions and speak to someone who can help you work through the details.</p><p>With 15, 17, 21 and 25 seaters and specialised access for disabled passengers, we welcome a wide range of groups and travel needs.</p></div></div></section>
  <section class="section pale-section"><div class="container"><div class="section-heading"><div>${eyebrow('THE PEOPLE BEHIND YOUR JOURNEY')}<h2>Care you can<br>put a name to.</h2></div><p>A direct conversation.<br>A thoughtfully arranged journey.</p></div><div class="manager-card"><div class="manager-monogram" aria-hidden="true">ML</div><div><p class="eyebrow">YOUR POINT OF CONTACT</p><h3>M Latif</h3><p>Licensed transport manager</p><p>For quotes, availability, school journeys and accessibility requirements, speak directly to M Latif.</p></div><a class="button" href="tel:+447971117677">${icon('phone')}07971 117677</a></div></div></section>
  <section class="section"><div class="container feature-grid"><article>${icon('shield')}<h3>Licensed & checked</h3><p>Fully licensed drivers who are DBS checked, and a licensed transport manager.</p></article><article>${icon('pin')}<h3>Lancashire approved</h3><p>Local roots and transport for the journeys that matter to our schools and communities.</p></article><article>${icon('access')}<h3>Everybody welcome</h3><p>An inclusive approach to travel, with specialised access discussed around individual needs.</p></article></div></section><section class="review-strip"><div class="container"><span class="google-g" aria-hidden="true">G</span><div><h2>Hear it from the people who travel with us.</h2><p>Visit our Google listing to check the latest passenger reviews.</p></div><a class="text-link" href="${googleReviews}" target="_blank" rel="noopener noreferrer">Find us on Google ${icon('arrow')}</a></div></section>${cta(base)}`;
}

function contact(base) {
  return `${pageHero(base,'CONTACT & ENQUIRIES','Every good journey<br><em>starts with hello.</em>','Tell us what you have in mind. M Latif will help you discuss the details, check availability and arrange a quote.')}
  <section class="section"><div class="container contact-grid"><aside class="contact-details">${eyebrow('LET’S TALK TRAVEL')}<h2>A real person.<br>A friendly welcome.</h2><a class="contact-method" href="tel:+447971117677"><span class="icon-tile">${icon('phone')}</span><span><small>CALL M LATIF</small><strong>07971 117677</strong></span></a><a class="contact-method" href="mailto:safetravel77@outlook.com"><span class="icon-tile">${icon('mail')}</span><span><small>EMAIL YOUR ENQUIRY</small><strong class="email-address">safetravel77@outlook.com</strong></span></a><div class="contact-person"><strong>M Latif</strong><span>Licensed transport manager</span><span>Hannah Coaches UK · Est. 2010</span></div><div class="access-note">${icon('access')}<h3>Everybody welcome.</h3><p>For specialised access, call us to discuss your boarding and travel requirements. You don’t need to share medical information in this form.</p></div><a class="text-link" href="${googleReviews}" target="_blank" rel="noopener noreferrer">Find us & check reviews on Google ${icon('arrow')}</a></aside>
  <div class="enquiry-card" id="enquiry"><p class="eyebrow">YOUR JOURNEY, YOUR WAY</p><h2>Let’s make a plan.</h2><p>Complete the details to prepare an email enquiry. You’ll review and send it in your own email app.</p><div class="form-completion enhanced-only"><div><span>Your enquiry</span><span id="form-completion-label">0 of 7 essentials completed</span></div><progress id="form-completion" max="7" value="0" aria-label="Required enquiry fields completed"></progress></div><form id="quote-form"><div class="form-grid"><div class="field"><label for="name">Your name <span>*</span></label><input id="name" name="name" autocomplete="name" required maxlength="100" placeholder="Full name"></div><div class="field"><label for="email">Email address <span>*</span></label><input id="email" name="email" type="email" autocomplete="email" required maxlength="160" placeholder="you@example.com"></div><div class="field"><label for="phone">Phone number <span>*</span></label><input id="phone" name="phone" type="tel" autocomplete="tel" required maxlength="30" placeholder="Your contact number"></div><div class="field"><label for="service">What’s the occasion? <span>*</span></label><select id="service" name="service" required><option value="">Choose a journey</option><option>School transport</option><option>Accessible transport</option><option>Airport transfer</option><option>Golf trip</option><option>Football trip</option><option>UK resort or weekend trip</option><option>Wedding or celebration</option><option>Other journey</option></select></div><div class="field"><label for="date">Travel date</label><input id="date" name="date" type="date"></div><div class="field"><label for="passengers">Number of passengers <span>*</span></label><input id="passengers" name="passengers" type="number" min="1" max="100" step="1" required placeholder="How many are travelling?"></div><div class="field"><label for="pickup">Pickup location <span>*</span></label><input id="pickup" name="pickup" required maxlength="200" placeholder="Town or postcode"></div><div class="field"><label for="destination">Destination <span>*</span></label><input id="destination" name="destination" required maxlength="200" placeholder="Where are you heading?"></div><div class="field full-field"><label for="details">A few more details</label><textarea id="details" name="details" rows="4" maxlength="1800" placeholder="Pickup time, return journey, luggage, equipment or access requirements…"></textarea></div></div><p class="form-note">Fields marked * are required. This is an enquiry, not a confirmed booking. We’ll agree availability, price and arrangements with you directly.</p><button class="button" type="submit">Prepare email enquiry ${icon('mail')}</button><p class="privacy-note">Your details stay in your browser until you choose to email them. <a href="#privacy">About your privacy</a></p></form>
  <div class="email-preview" id="email-preview" hidden role="status" tabindex="-1"><h3>Your enquiry is ready to review.</h3><p>Open your email app to send it to M Latif, or copy the enquiry and email it to <a href="mailto:safetravel77@outlook.com">safetravel77@outlook.com</a>. Nothing has been sent yet.</p><pre id="enquiry-text" tabindex="0" aria-label="Your prepared enquiry"></pre><div class="preview-actions"><a class="button" id="send-email" href="mailto:safetravel77@outlook.com">Open email app ${icon('mail')}</a><button type="button" class="button button-outline" id="copy-enquiry">Copy enquiry</button></div><p id="copy-status" aria-live="polite"></p></div><noscript><p>You can enquire directly by calling <a href="tel:+447971117677">07971 117677</a> or emailing <a href="mailto:safetravel77@outlook.com">safetravel77@outlook.com</a>. The enquiry builder requires JavaScript.</p></noscript></div></div></section>
  <section id="privacy" class="privacy-section"><div class="container"><h2>Your privacy & your enquiry</h2><p>This website does not use advertising cookies, analytics or an online booking database. The trip companion keeps your preparation plan in the current tab, unless you choose “Save on this device”. If selected, your plan is saved in this browser’s local storage and can be accessed by other users of the same browser. Switch saving off to remove the saved copy. Downloads and copied trip packs are under your control and are not sent to Hannah Coaches. The form prepares an email on your device; it does not submit your details to a website server. If you choose to send an email, your email provider handles delivery and Hannah Coaches UK receives the information to respond to your enquiry and arrange your requested transport. Please avoid including sensitive medical details. Stay searches share your destination and selected dates with Booking.com or Airbnb when you follow their links. Pickup and property details are only carried to our enquiry page for you to review. Accommodation bookings are handled directly by the provider. External services, including Google, have their own privacy policies.</p><p>For questions about your information, contact M Latif at <a href="mailto:safetravel77@outlook.com">safetravel77@outlook.com</a>.</p></div></section>`;
}

const content = { '': home, 'our-fleet': fleet, 'school-transport': school, 'airport-transfers': airports, 'trips-events': trips, 'stays-travel': stays, about, contact };

export function renderPage(page, base = '/') {
  const schema = { '@context': 'https://schema.org', '@type': 'LocalBusiness', name: 'Hannah Coaches UK', telephone: '+447971117677', email: 'safetravel77@outlook.com', foundingDate: '2010', areaServed: ['Lancashire', 'United Kingdom'], description: 'Minibus and coach hire, school and accessible transport, airport transfers, trips and events. 15, 17, 21 and 25 seaters.' };
  return `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title} | Hannah Coaches UK</title><meta name="description" content="${page.description}"><meta name="theme-color" content="#174bd7"><meta property="og:type" content="website"><meta property="og:title" content="${page.title} | Hannah Coaches UK"><meta property="og:description" content="${page.description}"><meta property="og:locale" content="en_GB"><link rel="icon" type="image/svg+xml" href="${base}assets/favicon.svg"><link rel="stylesheet" href="${base}assets/styles.css"><script type="application/ld+json">${JSON.stringify(schema)}</script><script src="${base}assets/client.js" defer></script><link rel="stylesheet" href="${base}assets/trip-tool.css">${page.slug === 'trips-events' ? `<script type="module" src="${base}assets/trip-tool.js"></script>` : ''}${page.slug === 'stays-travel' ? `<link rel="stylesheet" href="${base}assets/stays.css"><script type="module" src="${base}assets/stays.js"></script>` : ''}</head><body>${header(page,base)}<main id="main">${content[page.slug](base)}</main>${footer(base)}${planner(base)}</body></html>`;
}
