export function staysPlanner(base, icon) {
  return `<section class="stay-route"><div class="container"><ol><li><span>01</span>Find your place</li><li><span>02</span>Bring the group</li><li><span>03</span>Arrange the journey</li></ol></div></section>
  <section class="section stay-section" id="stay-planner"><div class="container"><div class="section-heading"><div><p class="eyebrow">A GOOD STAY STARTS WITH A PLAN</p><h2>The place to stay.<br><em>The way to get there.</em></h2></div><p>Explore accommodation, then bring your plans<br>back here for a Hannah Coaches enquiry.</p></div>
  <form id="stay-form" data-base="${base}" class="stay-layout enhanced-only">
    <div class="stay-workspace">
      <div class="stay-panel"><div class="stay-panel-heading"><span class="stay-step">01</span><div><h3>Where shall we go?</h3><p>Start with a UK destination. Dates can be flexible.</p></div></div>
      <div class="field"><label for="stay-destination">Town, region or destination <span>*</span></label><input id="stay-destination" name="destination" required maxlength="100" placeholder="e.g. Windermere, Lake District"></div>
      <div class="stay-chips" role="group" aria-label="Destination ideas"><span>Try somewhere:</span>${['Lake District','Blackpool','York','Manchester'].map(place=>`<button type="button" data-stay-place="${place}">${place}</button>`).join('')}</div>
      <div class="form-grid"><div class="field"><label for="stay-checkin">Check-in</label><input id="stay-checkin" name="checkin" type="date" aria-describedby="stay-date-help stay-date-error"></div><div class="field"><label for="stay-checkout">Check-out</label><input id="stay-checkout" name="checkout" type="date" aria-describedby="stay-date-help stay-date-error"></div></div>
      <p class="stay-hint" id="stay-date-help">Leave both dates blank if you’re still deciding.</p><p class="stay-error" id="stay-date-error" aria-live="polite"></p>
      <div class="stay-providers">
        <article class="stay-provider"><span class="provider-wordmark booking-wordmark">Booking.com</span><h4>Find your next check-in.</h4><p>Explore hotels, apartments and other places to stay.</p><a id="stay-booking" class="button" href="https://www.booking.com/" target="_blank" rel="noopener noreferrer">Search Booking.com <span aria-hidden="true">↗</span><span class="sr-only"> (opens a new tab)</span></a></article>
        <article class="stay-provider"><span class="provider-wordmark airbnb-wordmark">airbnb</span><h4>Find a place for your people.</h4><p>Explore homes and stays for your time away together.</p><a id="stay-airbnb" class="button button-outline" href="https://www.airbnb.co.uk/" target="_blank" rel="noopener noreferrer">Search Airbnb <span aria-hidden="true">↗</span><span class="sr-only"> (opens a new tab)</span></a></article>
      </div><p class="stay-hint">Searches open in a new tab. Check the destination and dates there, then set guests, children, rooms and access needs with the provider. Large groups may need several rooms or properties. If a provider resets the search, re-enter your destination and dates.</p><button type="button" class="stay-copy" id="stay-copy">Copy destination & dates ${icon('arrow')}</button><p class="stay-hint" id="stay-copy-status" role="status"></p></div>
      <div class="stay-panel" id="stay-transport"><div class="stay-panel-heading"><span class="stay-step">02</span><div><h3>Bring your people together.</h3><p>Already found a stay? Add it below, or enquire while you’re still choosing.</p></div></div>
      <div class="form-grid"><div class="field"><label for="stay-passengers">Coach passengers <span>*</span></label><input id="stay-passengers" name="passengers" type="number" min="1" max="100" step="1" required value="15"></div><div class="field"><label for="stay-pickup">Pickup town or postcode</label><input id="stay-pickup" name="pickup" maxlength="200" placeholder="e.g. Nelson, Lancashire"></div><div class="field"><label for="stay-status">Accommodation plans</label><select id="stay-status" name="status"><option>Still choosing</option><option>Shortlisted</option><option>Booked</option></select></div><div class="field"><label for="stay-property">Property name (optional)</label><input id="stay-property" name="property" maxlength="80" placeholder="Your hotel or accommodation"></div><div class="field full-field"><label for="stay-address">Property address or postcode (optional)</label><input id="stay-address" name="address" maxlength="140" placeholder="Helps us plan the right drop-off point"></div></div>
      <label class="check-control"><input type="checkbox" id="stay-access" name="accessible"><span>I’d like to discuss accessible transport</span></label><p class="stay-hint">Confirm step-free access and facilities with the accommodation separately. Discuss boarding needs, luggage and vehicle suitability with M Latif.</p></div>
    </div>
    <aside class="stay-summary"><div class="stay-summary-photo"><img src="${base}assets/country-road.jpg" alt="A winding country road through green hills" loading="lazy" width="1000" height="650"><span>YOUR NEXT GOOD MEMORY</span></div><div class="stay-summary-body"><p class="eyebrow">03 / THE JOURNEY TOGETHER</p><h3>Your stay.<br>Our journey.</h3><div id="stay-summary-content" aria-live="polite" aria-atomic="true"><strong id="stay-summary-destination">Somewhere to look forward to</strong><dl><div><dt>Time away</dt><dd id="stay-summary-nights">Flexible dates</dd></div><div><dt>Your group</dt><dd id="stay-summary-people">15 passengers</dd></div><div><dt>Accommodation</dt><dd id="stay-summary-status">Still choosing</dd></div></dl><p id="stay-capacity">Explore our 15-seater as a starting point.</p></div><p class="stay-summary-small">Seats, luggage space and accessible arrangements are subject to confirmation.</p><button class="button button-white" type="submit">Enquire with Hannah Coaches ${icon('arrow')}</button><p class="stay-summary-small">Your destination, dates and stay details carry into the enquiry. Travel dates start with check-in and check-out; tell us if you need different dates or times.</p><a class="stay-companion" href="${base}trips-events/#trip-tool">Next: prepare your group trip ${icon('arrow')}</a></div></aside>
  </form><noscript><div class="stay-panel"><h3>Find a stay, then arrange your transport.</h3><p>Explore accommodation on <a class="text-link" href="https://www.booking.com/" target="_blank" rel="noopener noreferrer">Booking.com</a> or <a class="text-link" href="https://www.airbnb.co.uk/" target="_blank" rel="noopener noreferrer">Airbnb</a>. Share your property, dates and passenger numbers with us.</p><a class="button" href="${base}contact/?service=UK+resort+or+weekend+trip">Enquire with Hannah Coaches ${icon('arrow')}</a></div></noscript>
  <div class="stay-separate"><span class="icon-tile">${icon('shield')}</span><div><h3>Two bookings. One well-planned trip.</h3><p>Book and pay for accommodation directly with your chosen provider. Hannah Coaches arranges transport separately. These are independent search links; we do not receive or import your accommodation booking. A transport enquiry is confirmed only once availability, price and arrangements have been agreed with M Latif.</p></div></div></div></section>`;
}
